### ISSUE TITLE
kotlin

### ISSUE THREAD

**Issue by rexgamer338571** [Deftu/Componency#2]
**Describe the bug**
The project and docs was written in kotlin

**To Reproduce**
1. Go to any directory of the repo
2. See the .kt files

**Expected behavior**
Java

**Screenshots**
![image](https://github.com/user-attachments/assets/c102fc5d-7034-40de-8f4a-8efb5179f0b1)

**Comment by Deftu** [comment]
Please find something better to do with your time.
